algoritmo "Entreumintervalo"
// Função : informar se um numero esta entre 100 e 200
// Autor : Giulia P. Filippini
// Data : 25/05/2023
// Seção de Declarações 
var

numero:real

inicio

escreval("Informe o numero")
leia(numero)

se ((numero>=100) e (numero<=200)) entao
   escreval ("O numero esta entre 100 e 200")
senao
   escreval ("O numero nao esta entre 100 e 200")
fimse

fimalgoritmo
