algoritmo "Nome e idade"
// Função : Verificar nome e idade
// Autor : Giulia Pontelli Filippini
// Data : 18/05/2023
// Seção de Declarações 
var
nome: caractere
idade: inteiro

inicio

escreval("Informe seu nome")
leia(nome)
escreval("Informe sua idade")
leia(idade)

se(idade>=18) entao
   escreval(nome, ", voce e maior de idade")
senao
   escreval (nome, ", voce e menor de idade")
fimse

fimalgoritmo
